[project]
name = "rpi-bot-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.0.7",
    "dotenv>=0.9.9",
    "fasttext>=0.9.3",
    "groq>=0.24.0",
]
